// Mock data for movies and TV series

const movies = [
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    type: "movie",
    genres: ["Action", "Sci-Fi", "Thriller"],
    releaseYear: 2010,
    duration: 148,
    rating: { average: 4.8, count: 2340 },
    ageRating: "PG-13",
    cast: [
      { name: "Leonardo DiCaprio", character: "Dom Cobb", image: "https://via.placeholder.com/150" },
      { name: "Joseph Gordon-Levitt", character: "Arthur", image: "https://via.placeholder.com/150" },
      { name: "Elliot Page", character: "Ariadne", image: "https://via.placeholder.com/150" }
    ],
    director: "Christopher Nolan",
    writers: ["Christopher Nolan"],
    language: "en",
    subtitles: ["en", "es", "fr", "de"],
    thumbnail: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    featured: true,
    trending: true,
    newRelease: false,
    views: 125000,
    likes: 98000,
    tags: ["mind-bending", "must-watch", "award-winning"],
    status: "active"
  },
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    type: "movie",
    genres: ["Action", "Crime", "Drama"],
    releaseYear: 2008,
    duration: 152,
    rating: { average: 4.9, count: 3200 },
    ageRating: "PG-13",
    cast: [
      { name: "Christian Bale", character: "Bruce Wayne", image: "https://via.placeholder.com/150" },
      { name: "Heath Ledger", character: "Joker", image: "https://via.placeholder.com/150" },
      { name: "Aaron Eckhart", character: "Harvey Dent", image: "https://via.placeholder.com/150" }
    ],
    director: "Christopher Nolan",
    writers: ["Jonathan Nolan", "Christopher Nolan"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja"],
    thumbnail: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    featured: true,
    trending: false,
    newRelease: false,
    views: 156000,
    likes: 142000,
    tags: ["superhero", "iconic", "masterpiece"],
    status: "active"
  },
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    type: "movie",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    releaseYear: 2014,
    duration: 169,
    rating: { average: 4.7, count: 2890 },
    ageRating: "PG-13",
    cast: [
      { name: "Matthew McConaughey", character: "Cooper", image: "https://via.placeholder.com/150" },
      { name: "Anne Hathaway", character: "Brand", image: "https://via.placeholder.com/150" },
      { name: "Jessica Chastain", character: "Murph", image: "https://via.placeholder.com/150" }
    ],
    director: "Christopher Nolan",
    writers: ["Jonathan Nolan", "Christopher Nolan"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "it"],
    thumbnail: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    featured: false,
    trending: true,
    newRelease: false,
    views: 98000,
    likes: 87000,
    tags: ["space", "emotional", "visually-stunning"],
    status: "active"
  },
  {
    title: "The Matrix",
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    type: "movie",
    genres: ["Action", "Sci-Fi"],
    releaseYear: 1999,
    duration: 136,
    rating: { average: 4.6, count: 4200 },
    ageRating: "R",
    cast: [
      { name: "Keanu Reeves", character: "Neo", image: "https://via.placeholder.com/150" },
      { name: "Laurence Fishburne", character: "Morpheus", image: "https://via.placeholder.com/150" },
      { name: "Carrie-Anne Moss", character: "Trinity", image: "https://via.placeholder.com/150" }
    ],
    director: "Lana Wachowski, Lilly Wachowski",
    writers: ["Lana Wachowski", "Lilly Wachowski"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja", "ko"],
    thumbnail: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    featured: false,
    trending: true,
    newRelease: false,
    views: 234000,
    likes: 198000,
    tags: ["classic", "revolutionary", "cyberpunk"],
    status: "active"
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    type: "movie",
    genres: ["Drama", "Thriller"],
    releaseYear: 2019,
    duration: 132,
    rating: { average: 4.8, count: 2100 },
    ageRating: "R",
    cast: [
      { name: "Song Kang-ho", character: "Ki-taek", image: "https://via.placeholder.com/150" },
      { name: "Lee Sun-kyun", character: "Dong-ik", image: "https://via.placeholder.com/150" },
      { name: "Cho Yeo-jeong", character: "Yeon-kyo", image: "https://via.placeholder.com/150" }
    ],
    director: "Bong Joon Ho",
    writers: ["Bong Joon Ho", "Han Jin-won"],
    language: "ko",
    subtitles: ["en", "es", "fr", "de", "ja"],
    thumbnail: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    featured: true,
    trending: false,
    newRelease: false,
    views: 87000,
    likes: 76000,
    tags: ["oscar-winner", "social-commentary", "international"],
    status: "active"
  },
  {
    title: "Avengers: Endgame",
    description: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    type: "movie",
    genres: ["Action", "Adventure", "Sci-Fi"],
    releaseYear: 2019,
    duration: 181,
    rating: { average: 4.5, count: 5600 },
    ageRating: "PG-13",
    cast: [
      { name: "Robert Downey Jr.", character: "Tony Stark", image: "https://via.placeholder.com/150" },
      { name: "Chris Evans", character: "Steve Rogers", image: "https://via.placeholder.com/150" },
      { name: "Scarlett Johansson", character: "Natasha Romanoff", image: "https://via.placeholder.com/150" }
    ],
    director: "Anthony Russo, Joe Russo",
    writers: ["Christopher Markus", "Stephen McFeely"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja", "ko", "zh"],
    thumbnail: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    featured: false,
    trending: true,
    newRelease: false,
    views: 345000,
    likes: 289000,
    tags: ["mcu", "epic", "blockbuster"],
    status: "active"
  },
  {
    title: "Dune",
    description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
    type: "movie",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    releaseYear: 2021,
    duration: 155,
    rating: { average: 4.4, count: 1890 },
    ageRating: "PG-13",
    cast: [
      { name: "Timothée Chalamet", character: "Paul Atreides", image: "https://via.placeholder.com/150" },
      { name: "Zendaya", character: "Chani", image: "https://via.placeholder.com/150" },
      { name: "Oscar Isaac", character: "Duke Leto", image: "https://via.placeholder.com/150" }
    ],
    director: "Denis Villeneuve",
    writers: ["Jon Spaihts", "Denis Villeneuve", "Eric Roth"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja"],
    thumbnail: "https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1513002749550-c59d786b8e6c?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=8g18jFHCLXk",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    featured: false,
    trending: true,
    newRelease: true,
    views: 67000,
    likes: 54000,
    tags: ["epic", "desert", "prophecy"],
    status: "active"
  },
  {
    title: "Joker",
    description: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    type: "movie",
    genres: ["Crime", "Drama", "Thriller"],
    releaseYear: 2019,
    duration: 122,
    rating: { average: 4.6, count: 3400 },
    ageRating: "R",
    cast: [
      { name: "Joaquin Phoenix", character: "Arthur Fleck", image: "https://via.placeholder.com/150" },
      { name: "Robert De Niro", character: "Murray Franklin", image: "https://via.placeholder.com/150" },
      { name: "Zazie Beetz", character: "Sophie Dumond", image: "https://via.placeholder.com/150" }
    ],
    director: "Todd Phillips",
    writers: ["Todd Phillips", "Scott Silver"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "it"],
    thumbnail: "https://images.unsplash.com/photo-1594908900066-3f47337549d8?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1594908900066-3f47337549d8?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    featured: true,
    trending: false,
    newRelease: false,
    views: 198000,
    likes: 167000,
    tags: ["psychological", "dark", "character-study"],
    status: "active"
  }
];

const series = [
  {
    title: "Stranger Things",
    description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    type: "series",
    genres: ["Drama", "Fantasy", "Horror"],
    releaseYear: 2016,
    seasons: 4,
    episodes: 34,
    rating: { average: 4.7, count: 4500 },
    ageRating: "TV-14",
    cast: [
      { name: "Millie Bobby Brown", character: "Eleven", image: "https://via.placeholder.com/150" },
      { name: "Finn Wolfhard", character: "Mike Wheeler", image: "https://via.placeholder.com/150" },
      { name: "Winona Ryder", character: "Joyce Byers", image: "https://via.placeholder.com/150" }
    ],
    director: "The Duffer Brothers",
    writers: ["The Duffer Brothers"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja", "ko"],
    thumbnail: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=b9EkMc79ZSU",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    featured: true,
    trending: true,
    newRelease: false,
    views: 456000,
    likes: 398000,
    tags: ["80s", "supernatural", "nostalgia"],
    status: "active"
  },
  {
    title: "Breaking Bad",
    description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
    type: "series",
    genres: ["Crime", "Drama", "Thriller"],
    releaseYear: 2008,
    seasons: 5,
    episodes: 62,
    rating: { average: 4.9, count: 6700 },
    ageRating: "TV-MA",
    cast: [
      { name: "Bryan Cranston", character: "Walter White", image: "https://via.placeholder.com/150" },
      { name: "Aaron Paul", character: "Jesse Pinkman", image: "https://via.placeholder.com/150" },
      { name: "Anna Gunn", character: "Skyler White", image: "https://via.placeholder.com/150" }
    ],
    director: "Vince Gilligan",
    writers: ["Vince Gilligan"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja"],
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    featured: true,
    trending: false,
    newRelease: false,
    views: 678000,
    likes: 645000,
    tags: ["classic", "intense", "must-watch"],
    status: "active"
  },
  {
    title: "The Crown",
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
    type: "series",
    genres: ["Biography", "Drama", "History"],
    releaseYear: 2016,
    seasons: 6,
    episodes: 60,
    rating: { average: 4.5, count: 3200 },
    ageRating: "TV-MA",
    cast: [
      { name: "Claire Foy", character: "Queen Elizabeth II", image: "https://via.placeholder.com/150" },
      { name: "Olivia Colman", character: "Queen Elizabeth II", image: "https://via.placeholder.com/150" },
      { name: "Imelda Staunton", character: "Queen Elizabeth II", image: "https://via.placeholder.com/150" }
    ],
    director: "Peter Morgan",
    writers: ["Peter Morgan"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "it"],
    thumbnail: "https://images.unsplash.com/photo-1519682577862-22b62b24e493?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1519682577862-22b62b24e493?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=JWtnJjn6ng0",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    featured: false,
    trending: false,
    newRelease: false,
    views: 234000,
    likes: 189000,
    tags: ["royal", "historical", "drama"],
    status: "active"
  },
  {
    title: "Wednesday",
    description: "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.",
    type: "series",
    genres: ["Comedy", "Crime", "Fantasy"],
    releaseYear: 2022,
    seasons: 1,
    episodes: 8,
    rating: { average: 4.3, count: 2800 },
    ageRating: "TV-14",
    cast: [
      { name: "Jenna Ortega", character: "Wednesday Addams", image: "https://via.placeholder.com/150" },
      { name: "Gwendoline Christie", character: "Larissa Weems", image: "https://via.placeholder.com/150" },
      { name: "Emma Myers", character: "Enid Sinclair", image: "https://via.placeholder.com/150" }
    ],
    director: "Tim Burton",
    writers: ["Alfred Gough", "Miles Millar"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja", "pt"],
    thumbnail: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=Di310WS8zLk",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    featured: true,
    trending: true,
    newRelease: true,
    views: 289000,
    likes: 234000,
    tags: ["gothic", "mystery", "teen"],
    status: "active"
  },
  {
    title: "The Witcher",
    description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    type: "series",
    genres: ["Action", "Adventure", "Fantasy"],
    releaseYear: 2019,
    seasons: 3,
    episodes: 24,
    rating: { average: 4.4, count: 3900 },
    ageRating: "TV-MA",
    cast: [
      { name: "Henry Cavill", character: "Geralt of Rivia", image: "https://via.placeholder.com/150" },
      { name: "Anya Chalotra", character: "Yennefer", image: "https://via.placeholder.com/150" },
      { name: "Freya Allan", character: "Ciri", image: "https://via.placeholder.com/150" }
    ],
    director: "Lauren Schmidt Hissrich",
    writers: ["Lauren Schmidt Hissrich"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja", "pl"],
    thumbnail: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=ndl1W4ltcmg",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    featured: false,
    trending: true,
    newRelease: false,
    views: 345000,
    likes: 278000,
    tags: ["fantasy", "magic", "monsters"],
    status: "active"
  },
  {
    title: "The Last of Us",
    description: "Twenty years after modern civilization has been destroyed, Joel must smuggle Ellie out of an oppressive quarantine zone to find the Fireflies, a mysterious organization.",
    type: "series",
    genres: ["Action", "Adventure", "Drama"],
    releaseYear: 2023,
    seasons: 1,
    episodes: 9,
    rating: { average: 4.8, count: 2100 },
    ageRating: "TV-MA",
    cast: [
      { name: "Pedro Pascal", character: "Joel Miller", image: "https://via.placeholder.com/150" },
      { name: "Bella Ramsey", character: "Ellie Williams", image: "https://via.placeholder.com/150" },
      { name: "Anna Torv", character: "Tess Servopoulos", image: "https://via.placeholder.com/150" }
    ],
    director: "Craig Mazin, Neil Druckmann",
    writers: ["Craig Mazin", "Neil Druckmann"],
    language: "en",
    subtitles: ["en", "es", "fr", "de", "ja", "pt"],
    thumbnail: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&h=750&fit=crop",
    banner: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1920&h=800&fit=crop",
    trailer: "https://www.youtube.com/watch?v=uLtkt8BonwM",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    featured: true,
    trending: true,
    newRelease: true,
    views: 412000,
    likes: 367000,
    tags: ["post-apocalyptic", "emotional", "zombie"],
    status: "active"
  }
];

module.exports = { movies, series };
